package com.politeai.domain.transform.model;

public enum ValidationIssueType {
    EMOJI,
    FORBIDDEN_PHRASE,
    HALLUCINATED_FACT,
    ENDING_REPETITION,
    LENGTH_OVEREXPANSION,
    PERSPECTIVE_ERROR,
    LOCKED_SPAN_MISSING,
    REDACTED_REENTRY,
    REDACTION_TRACE,
    CORE_NUMBER_MISSING,
    CORE_DATE_MISSING,
    SOFTEN_CONTENT_DROPPED,
    SECTION_S2_MISSING
}
